envVars:
  - key: PGHOST
    fromDatabase:
      name: odoo-db
      property: host
  - key: PGPORT
    fromDatabase:
      name: odoo-db
      property: port
  - key: PGUSER
    fromDatabase:
      name: odoo-db
      property: user
  - key: PGPASSWORD
    fromDatabase:
      name: odoo-db
      property: password
  - key: PGDATABASE
    fromDatabase:
      name: odoo-db
      property: database
